Декомпозировать login, registration, profile
frontend-park-mail-ru/2021_1_Execute pull request #11
Opened 2021-02-22 01:57 UTC by ZhukDima

2021-02-22 10:18 UTC, AlexisOMG requested changes

2021-02-22 10:18 UTC, AlexisOMG commented on src/asker/asker.js
> +class AskerModule {
AskerModule -> Validator

2021-02-22 18:37 UTC, AlexisOMG approved these changes

2021-02-23 11:41 UTC, gavroman commented on server.js
> +const defineSites = ['/', '/login', '/profile', '/registration'];
Это конечно круто, но в будущем тут могут возникнуть проблемки. При каждом новом роуте, придется сюда что-то добавлять, а это уже не отдельный независимый сервер. В идеале он должен быть написан так, чтоб чтоб его можно было выдернуть в другой проект и никак не трогать. Как он дальше будет обрабатывать роуты типа /profile/gavroman или /board/ewe7ghjdfk3j? Давай если не нашли файлик, тогда вернем index.html

2021-02-23 11:43 UTC, gavroman commented on src/index.js
> +const router = {
чет не оч роутер, давай норм класс сделаем в utils, с методами перехода по роуту и добавлением роута

2021-02-23 11:45 UTC, gavroman commented on src/index.js
> +const profile = {};
для чего это нужно и как используется?

2021-02-23 11:46 UTC, gavroman commented on src/index.js
> +const tryToConnect = [window.location.pathname, '/login', '/profile'];
почему так? Нужно открывать ту страничку на которую пришел пользователь, тот роут, который в адресной строке

2021-02-23 11:47 UTC, gavroman commented on src/login/login.handlebars
> +            class="menu-linebtn menu-linebtn-black menu-linebtn-active-red">Регистрация</button>
го тут сделаем ссылку вместо кнопки, она же просто на регистрацию редиректит?

2021-02-23 11:48 UTC, gavroman commented on src/login/login.js
> +}
давай снесем этот файлик, раз он не нужен

2021-02-23 11:49 UTC, gavroman commented on src/login/loginController.js
> +    ValidationModule.exitProfile(profile);
не совсем понимаю, почему в валиации есть какой-то разлогин

2021-02-23 11:49 UTC, gavroman commented on src/login/loginController.js
> +    this.view = new LoginView(this.eventBus, profile);
в конструктор 2 строчки выше

2021-02-23 11:50 UTC, gavroman commented on src/login/loginController.js
> +    return true;
зачем оно что-то возвращает?

2021-02-23 11:53 UTC, gavroman commented on src/login/loginModel.js
> +    this.eventBus.subscribe('clickGotoRegistration', () => this.gotoRegistration());
договаривались же вынести все события eventBus в константы. 
`export const loginEvents = {`
`    clickEnter: 'login.view.clickEnter',`
`    clickGoToRegistration: 'login.view.clickGoToRegistration'`
}

2021-02-23 11:59 UTC, gavroman commented on src/login/loginModel.js
> +      case ValidationModule.UNCORRECT_SERVERANS:
ответ сервера, что логин или пароль неверный, не имеет к валидации никакого отношения. Вадидация данных на фронте - это просто проверка на нужную длину, наличие обязательных символов и отсутствие недопустимых, она не делает никаких запросов никуда

2021-02-23 12:01 UTC, gavroman commented on src/login/loginModel.js
> +    this.eventBus.call('registration');
зачем эта функция? событие тригерится во вьюхе по нажатию на кнопку, контроллер подписан на это событие и сразу редиректит. А вообще все редиректы можно и нужно делать через ссылки

2021-02-23 12:04 UTC, gavroman commented on src/login/loginView.js
> +    this.profile = profile;
во вьюхе не должно быть никаких данных

2021-02-23 12:05 UTC, gavroman commented on src/login/loginView.js
> +    this.eventBus.subscribe('login-warning', () => {
го вынесем подписки в конструктор, `this.eventBus.subscribe('login-warning', this.handleLoginWarning)`

2021-02-23 12:08 UTC, gavroman commented on src/login/loginView.js
> +      if (this.profile.correct_username === ValidationModule.UNCORRECT_PARSE) {
насколько я понял, тебе тут нужно понять, что именно не валидно, логин или пароль. Пусть модеька об этом гвоорит сразу и кидает событие либо loginInvalid, либо passwordInvalid. Либо просто invalid, а в параметре что именно - `eb.call(invalidInput, [InputFields.login, InputFields.password])` - массив на случай если несколько полей невалидны

2021-02-23 12:09 UTC, gavroman commented on src/login/loginView.js
> +    this.eventBus.subscribe('login-error', () => {
ну тут тоже, подписку в конструктор, обработку в отдельную функцию

2021-02-23 12:16 UTC, gavroman commented on src/login/loginView.js
> +      TemporaryReplacement.forTwoSeconds(inputPassword.parentElement.style, 'color', '#e34a00');
штука крутая и удобная, но 
1) Обращаясь к parentElement ты привязываешься к верстке, которая может измениться, поэтому давай доставать по айдишнику
2) го лучше навешивать класс вместо style
3) с навешиванием класса отлично справляется `classList.add/remove` и скорее всего делает это оптимальнее
давай подумаем, можно ли твой модуль как-то дополнить/изменить с учетов этих 3 моментиков

2021-02-23 12:17 UTC, gavroman commented on src/profile.html
> +            <button class="menu-linebtn menu-linebtn-black menu-linebtn-active-red"
не, давай оставим ссылку, тогда не нужно будет ручками обрабатывать переход

2021-02-23 12:18 UTC, gavroman commented on src/profile/profileController.js
> +}
это я так понял тоже выпиливаем, раз есть разделение на mvc

2021-02-23 12:19 UTC, gavroman commented on src/profile/profileModel.js
> +      email, username, password, repeatPassword,
го тогда сразу объект передавать, только доку напиши, чтоб было понятно что в его полях

2021-02-23 12:20 UTC, gavroman commented on src/profile/profileView.js
> +    this.profile = profile;
никаких сохранений данных во вьюхе

2021-02-23 12:22 UTC, gavroman commented on src/profile/profileView.js
> +    root.innerHTML = Handlebars.templates.profile(this.profile);
рендер должен принимать данные, которые он будет рендерить, а сейчас он их откуда-то магически берет (и кстати может изменить, что неправильно)

2021-02-23 12:22 UTC, gavroman commented on src/profile/profileView.js
> +    this.eventBus.subscribe('profile-success', () => {
по этому в другом файлике отписал, подписку в конструктор, обработку в отдельные функции

2021-02-23 12:23 UTC, gavroman commented on src/registration/registration.handlebars
> +        <button id="goto-login" class="menu-linebtn menu-linebtn-black menu-linebtn-active-red">Я уже
в ссылку

2021-02-23 12:24 UTC, gavroman commented on src/registration/registration.js
> +}
тоже лишний файлик получается

2021-02-23 12:24 UTC, gavroman commented on src/registration/registrationController.js
> +    ValidationModule.exitProfile(profile);
тут кажется уже кажется писал, валидация не должна разлогинивать и тем более ее не доложно быть в конструкторе

2021-02-23 12:25 UTC, gavroman commented on src/registration/registrationController.js
> +    this.eventBus.subscribe('profile', () => router.go('/profile'));
кстати, если сделать ссылки вместо кнопок, то не нужно будет ручками редиректить

2021-02-23 12:28 UTC, gavroman commented on src/registration/registrationModel.js
> +      this.profile[key] = value;
Я так понял, этот объектик один на все приложение, что довольно опасно. Напиши если интересно как сделать грамотно, подумаем вместе

2021-02-23 12:29 UTC, gavroman commented on src/registration/registrationView.js
> +      inputEMail.value, inputUserName.value, inputPassword.value, inputRepeatPassword.value));
много параметров, го объект

2021-02-23 12:29 UTC, gavroman commented on src/registration/registrationView.js
> +}
остальное аналогично остальным вьюхам

2021-02-23 12:30 UTC, gavroman commented on src/utils/temporaryReplacement.js
> +/* eslint-disable no-underscore-dangle */
чего тут задизейбленно?

2021-02-23 12:32 UTC, gavroman commented on src/utils/temporaryReplacement.js
> +   * @param {*} replacement
еще 1 параметр потерялся

2021-02-23 12:41 UTC, gavroman commented on src/validation/validation.js
> +}
очень много логики в этом файле, и не вся она должна быть тут. Тут точно не должно быть никакого взаимодействия с беком, сохранения данных и сравнения. Опять же этот модуль должен быть максимально прозрачным и не привязанным к конкретному приложению. Представь, что ты нашел где-то пакет- валидатор тип такого (https://www.npmjs.com/package/validator), он просто говорит true/false. Здесь же написано куча всего и немного реальной валидации. Предлагаю сделать тут набор функций, даже не класс, например:
`export const validateEmail(email) => {}`
возвращать она будет код, в котором либо ок, либо не ок и что не ок

2021-02-23 12:48 UTC, gavroman commented
общие моментики
1) не обязательно везде писать Module, оно и так модуль)
2) все что можно нужно выносить в константы - например события eventBus'a
3) го еще снесем лишние файлики и удалим файлики с html
4) css надо тоже разложить в папочки модулей или в отдельную папочку
5) редиректы можно и нужно сделать через ссылки (`<a href="...">Регитсрация</a>`)

2021-02-23 13:06 UTC, ZhukDima commented on src/index.js
> +const router = {
router должен Алексей написать, а это пока так - заглушка

2021-02-23 13:08 UTC, ZhukDima commented on src/index.js
> +const profile = {};
общее пространство где хранятся данные о пользователе - username, password и др. А чтобы все модули имели одни и теже данные - передаю общий объект, который изначально пуст

2021-02-23 13:12 UTC, ZhukDima commented on src/login/loginController.js
> +    ValidationModule.exitProfile(profile);
при выходе из профиля (или принудительном переходе в логин) я на вызываю выход пользователя, а валидация это делает из концепции "я тебя породил - я тебя и уничтожу" =P

2021-02-26 15:29 UTC, merged