Сверстать форму логина
frontend-park-mail-ru/2021_1_Execute pull request #2
Opened 2021-02-16 09:37 UTC by ZhukDima

2021-02-16 09:38 UTC, ZhukDima commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сверстать форму логина](https://trello.com/c/wnb5WHmK/1-%D1%81%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%B0%D1%82%D1%8C-%D1%84%D0%BE%D1%80%D0%BC%D1%83-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BD%D0%B0)

2021-02-16 11:05 UTC, ZhukDima commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сверстать форму регистрации](https://trello.com/c/vQ4Toxvw/2-%D1%81%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%B0%D1%82%D1%8C-%D1%84%D0%BE%D1%80%D0%BC%D1%83-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8)

2021-02-16 12:58 UTC, ZhukDima commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать простейший сервер](https://trello.com/c/lbVsWAeV/4-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%B5%D0%B9%D1%88%D0%B8%D0%B9-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80)

2021-02-17 06:56 UTC, gavroman commented on server.js
> +const fs = require("fs");
го одинарные кавычки

2021-02-17 06:56 UTC, gavroman commented on server.js
> +const port = 3000
;

2021-02-17 06:59 UTC, gavroman commented on src/login.css
> +}
\n

2021-02-17 07:01 UTC, gavroman commented on src/main.css
> +        font-size: 180px !important;
круто, что подумал про разные размеры экрана, но `!important`. В тп будет лекция про адаптивную верстку, там расскажут как надо. Предлагаю пока выпилить, или передалеть без `!important`

2021-02-17 07:02 UTC, gavroman commented on src/login.html
> +</html>
\n

2021-02-17 07:03 UTC, gavroman commented on src/checkin.html
> +            <input type="password" placeholder="Повторите пароль" name="" value="">
го снесем пустые атрибуты во всех инпутах

2021-02-17 07:05 UTC, gavroman commented on src/checkin.html
> +            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill"
нигде не нашел объявления классов `bi bi-lock-fill` давай уберем если не нужны

2021-02-17 07:05 UTC, gavroman commented on src/checkin.css
> +}
\n

2021-02-17 07:08 UTC, gavroman commented on src/checkin.css
> +    transform: translate(-50%, -50%);
не лучший способ центрировать дивак, попробуй `margin: 0 auto 0;` или 
`display: flex;` 
`justify-content: center;` 
`align-items: center;`

2021-02-17 07:10 UTC, gavroman requested changes
отписал пару мелочей, круто, что написал свой сервак, почему не стал использовать https://expressjs.com/ru/ ?

2021-02-17 08:19 UTC, ZhukDima commented on src/main.css
> +        font-size: 180px !important;
![0e71e60730cb6ae054af4f66c2ca28a2.jpg](https://user-images.githubusercontent.com/55634168/108175569-fdb7dc80-7111-11eb-94da-95dde94417b0.jpg)

2021-02-18 07:36 UTC, gavroman commented on src/checkin.html
> +<body class="menu-body-center">
давай лучше сделаем еще 1 дивак с `class="menu-body-center"` вместо навешивания класса на `body`

2021-02-18 15:03 UTC, merged