Сделал кнопке красиво
frontend-park-mail-ru/2021_1_Execute pull request #25
Opened 2021-03-11 17:43 UTC by ZhukDima

2021-03-11 17:51 UTC, gavroman commented on src/profile/profileModel.js
> +      profileAvatarUpload(profile.avatar)
1) на 59 сроке большой ифак получается, давай так `if (!correctChangeProfile(profile, callError)) return;`
2) а если в `profile` нет поля `avatar`? Выглядит как если я меняю что-то другое кроме авы, ава все равно шлется, даже если в инпуте нет файла. Давай слать аву, только если она есть в инпуте

2021-03-11 18:03 UTC, gavroman requested changes

2021-03-11 18:03 UTC, gavroman commented on src/profile/profile.handlebars
> +            <form enctype="multipart/form-data">
а зачем форма? разве без нее не работает?

2021-03-11 18:04 UTC, gavroman commented on src/profile/profileModel.js
> +    if (profile.avatar !== undefined) {
давай просто `if (profile.avatar)`

2021-03-11 19:03 UTC, MKondakova commented
Ты убрал дефолтный аватар, а он теперь где будет выставляться?

2021-03-12 05:55 UTC, gavroman commented on src/profile/profileModel.js
> +  changeAvatar({ avatar }) {
так давай сразу сюда только аву, зачем весь профиль

2021-03-12 05:56 UTC, gavroman commented on src/profile/profileView.js
>        avatar: this.inputAvatar.files[0],
го сразу аву кидать, зачем объект

2021-03-12 06:13 UTC, merged