Рефактор requestToServer.js
frontend-park-mail-ru/2021_1_Execute pull request #31
Opened 2021-03-18 19:59 UTC by MKondakova

2021-03-18 20:00 UTC, MKondakova commented
![](https://github.trello.services/images/mini-trello-icon.png) [Отрефакторить requestToServer 🛠](https://trello.com/c/xRN8w9S3/29-%D0%BE%D1%82%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D1%82%D1%8C-requesttoserver-%F0%9F%9B%A0)

2021-03-19 00:57 UTC, ZhukDima requested changes

2021-03-19 00:57 UTC, ZhukDima commented on src/profile/profileModel.js
> +  myProfilePatch, myProfileGet, exit, myProfileAvatarUpload,
ну my - как-то совсем по дурацки. го что-нибудь другое? например our или comrad))

2021-03-19 00:57 UTC, ZhukDima commented on src/profile/profileModel.js
> -    if (avatar.size > 2 * 1024 * 1024) {
зачем выпилила проверку?

2021-03-19 00:57 UTC, ZhukDima commented on src/login/loginModel.js
> +      login(profile)
если решила уйти от loginForm, то точно не на просто login - у нас этих логинов - пруд пруди: это и у роутера путь на сайт, и у ивент баса переброска запроса, и тут ещё будет - что-нибудь более понятное надо

2021-03-19 10:21 UTC, MKondakova commented on src/profile/profileModel.js
> +  myProfilePatch, myProfileGet, exit, myProfileAvatarUpload,
Могу убрать my и мы условимся, что это профиль текущего юзера, а чужие будут с byId

2021-03-19 10:21 UTC, MKondakova commented on src/profile/profileModel.js
> -    if (avatar.size > 2 * 1024 * 1024) {
Ой, случайно)

2021-03-19 10:22 UTC, MKondakova commented on src/login/loginModel.js
> +      login(profile)
Ты ведь логин этот импортишь из файла requestsToServer

2021-03-19 10:24 UTC, ZhukDima commented on src/profile/profileModel.js
> +  myProfilePatch, myProfileGet, exit, myProfileAvatarUpload,
давай

2021-03-19 10:25 UTC, ZhukDima commented on src/profile/profileModel.js
> -    if (avatar.size > 2 * 1024 * 1024) {
ну тогда верни)

2021-03-19 21:10 UTC, ZhukDima approved these changes

2021-03-20 06:22 UTC, merged