Main page Reforged
frontend-park-mail-ru/2021_1_Execute pull request #37
Opened 2021-03-29 13:39 UTC by ZhukDima

2021-03-29 13:39 UTC, ZhukDima commented
![](https://github.trello.services/images/mini-trello-icon.png) [Верстка главной страницы](https://trello.com/c/dvP6Tv91/32-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B9-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B)

2021-03-29 13:50 UTC, gavroman commented on src/css/header.css
> +  vertical-align: middle;
давай на флексы православные

2021-03-29 13:52 UTC, gavroman commented on src/css/mainPage.css
> +} */
раскоменчиваем/выпиливаем

2021-03-29 13:55 UTC, gavroman commented on src/css/mainPage.css
> +  background-position: center center;
почему не `background-position: center;`

2021-03-29 13:57 UTC, gavroman commented on src/css/mainPage.css
> +  -webkit-box-orient: vertical; /* Вертикальная ориентация */
что за зло и для чего?

2021-03-29 13:59 UTC, ZhukDima commented on src/css/mainPage.css
> +  -webkit-box-orient: vertical; /* Вертикальная ориентация */
чтобы многострочный текст обрезался 
![image](https://user-images.githubusercontent.com/55634168/112847872-2d161d80-90b0-11eb-9d7f-b9e9751f40f2.png)

2021-03-29 14:02 UTC, gavroman commented
из этого мра еще не все пофикшено https://github.com/frontend-park-mail-ru/2021_1_Execute/pull/36

2021-03-29 14:04 UTC, gavroman requested changes

2021-03-29 14:04 UTC, gavroman commented on src/css/mainPage.css
> +  -webkit-box-orient: vertical; /* Вертикальная ориентация */
так вот же https://github.com/frontend-park-mail-ru/2021_1_Execute/pull/37/files#diff-ee3e9fba266f3674d450003423840c5a9ae6469be92d8cfda8ba5b231a09332cR95

2021-03-29 14:11 UTC, ZhukDima commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать MVC mainPage](https://trello.com/c/TWlpRPgv/45-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-mvc-mainpage)

2021-03-31 08:28 UTC, MKondakova requested changes

2021-03-31 08:28 UTC, MKondakova commented on src/css/menu.css
> +  margin-right: calc(100vw - 100%);
Объясни, для чего это?

2021-03-31 08:28 UTC, MKondakova commented on src/mainPage/mainPageEvents.js
> +  repeatPasswordErrorValidation: 'Пароли не совпали',
при каких ситуациях тебе это понадобится?

2021-03-31 08:28 UTC, MKondakova commented on src/mainPage/mainPageView.js
> +  }
html в модели?

2021-03-31 08:28 UTC, MKondakova commented on src/mainPage/mainPageModel.js
> +
а если человек не авторизован?

2021-03-31 11:27 UTC, MKondakova commented
и еще при успешной регистрации/авторизации надо на главную перенаправлять

2021-03-31 15:14 UTC, MKondakova commented
http://89.208.199.114:4030/login/
тык

2021-03-31 17:38 UTC, MKondakova commented on src/mainPage/mainPageView.js
> +    this.checker = makeChecker(this);
где ты это используешь?

2021-03-31 18:21 UTC, ZhukDima commented on src/css/menu.css
> +  margin-right: calc(100vw - 100%);
Когда появляется скрол справа он сдвигает всю страницу влево, а это - обратный сдвиг вправо (он как раз равен 100vw - 100%)

2021-03-31 19:27 UTC, MKondakova approved these changes

2021-04-01 07:17 UTC, gavroman commented on src/css/header.css
> +  vertical-align: middle;
го флексы использовать

2021-04-01 07:18 UTC, gavroman commented on src/css/mainPage.css
> +.grid-desk h4 {
го селектор по классу

2021-04-01 07:19 UTC, gavroman commented on src/css/mainPage.css
> +  -webkit-box-orient: vertical; /* Вертикальная ориентация */
обсужадали же, почему не   
`white-space: nowrap;`
`overflow: hidden; `
`text-overflow: ellipsis;`

2021-04-01 07:21 UTC, gavroman commented on src/header/header.handlebars
> +    </picture>
зачем пикчер? почему не img?

2021-04-01 07:22 UTC, gavroman commented on src/mainPage/mainPageModel.js
> +    Promise.all([
крута!

2021-04-01 07:23 UTC, gavroman commented on src/mainPage/mainPageModel.js
> +  clickAddDesk(name) {
давай над неймингом поработаем, в случае модельки это не клик, это просто добавление доски, оно может быть и по нажатию на хоткей какой-то

2021-04-01 07:24 UTC, gavroman commented on src/mainPage/mainPageView.js
> +    });
что делет эта обработка даных? почему она не в модели?

2021-04-01 16:50 UTC, MKondakova commented on src/header/header.handlebars
> +    </picture>
Тут это сделано для того, чтобы лого менялось от размера

2021-04-01 16:53 UTC, gavroman commented on src/header/header.handlebars
> +    </picture>
Тогда делайте дивак с фоном

2021-04-01 18:04 UTC, gavroman commented on src/css/header.css
> +  float: left;
зачем `float: left` если `display: flex`?

2021-04-01 18:08 UTC, gavroman commented on src/mainPage/mainPageView.js
> + */
зачем коменты?

2021-04-01 18:10 UTC, gavroman commented on src/css/mainPage.css
> +  -webkit-box-orient: vertical; /* Вертикальная ориентация */
а с этим что?

2021-04-01 18:30 UTC, merged