Реализовать Post методы на странице доски
frontend-park-mail-ru/2021_1_Execute pull request #40
Opened 2021-04-11 18:00 UTC by ZhukDima

https://trello.com/c/xj1cBxzY/49-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-post-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D0%B4%D0%BE%D1%81%D0%BA%D0%B8

2021-04-11 18:04 UTC, ZhukDima commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать Post методы на странице доски](https://trello.com/c/xj1cBxzY/49-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-post-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D0%B4%D0%BE%D1%81%D0%BA%D0%B8)

2021-04-12 07:22 UTC, gavroman commented on src/utils/router.js
> +const standardizedPath = (path) => arrayToPath(pathToArray(path));
что оно делает и зачем?

2021-04-12 07:23 UTC, gavroman commented on src/boardPage/boardPageController.js
> +    this.eventBus.call(BoardPageEvent.getData, +pathArr[0]);
а как будет работать /board/5/task/4?

2021-04-12 07:25 UTC, gavroman commented on src/boardPage/boardPageModel.js
> +    this.eventBus.subscribe(BoardPageEvent.clickAddTask, (...all) => this.addTask(...all));
ненене, давай не увелкаться и не использовать спред везде) Го писать конкретные аргументы

2021-04-12 07:27 UTC, gavroman commented on src/boardPage/boardPageModel.js
> +   * @param {string} name
не хватает параметров

2021-04-12 07:29 UTC, gavroman commented on src/boardPage/boardPageView.js
> +      'click', () => this.eventBus.call(BoardPageEvent.clickAddTask, +elem.id.slice(12), ind, 'Новая задача'),
Какие-то подозрительные слайсы с волшебными чиселками. Го писать айдишники в датаатрибуты https://developer.mozilla.org/ru/docs/Learn/HTML/Howto/Use_data_attributes

2021-04-12 07:31 UTC, gavroman commented on src/boardPage/boardPageView.js
> +        +newHTMLElementAddTask.id.slice(12), position, 'Новая задача'))(this.buttonsAddTask.length),
непонятно и нечитаемо

2021-04-12 07:32 UTC, gavroman commented on src/index.js
> +router.addRoute('main', (...all) => mainPageController.start(...all));
почему везде спреды?

2021-04-12 11:35 UTC, gavroman commented on src/utils/router.js
> +const standardizedPath = (path) => (typeof path === 'string' ? `/${(path.match(/[^/]{1,}/g) || []).join('/')}` : path);
что и зачем делает эта функция?

2021-04-12 11:37 UTC, gavroman commented on src/utils/router.js
> +     * @type {[path, handler][]}
почему не объект где ключ регулярка?

2021-04-12 11:38 UTC, gavroman commented on src/index.js
> +router.addRoute(/^\/board\/(?<id>\d+)$/, ({ groups }) => boardPageController.start(+groups?.id));
что такое groups

2021-04-12 11:40 UTC, gavroman commented on src/boardPage/boardPageView.js
> +    this.buttonsAddTask.forEach((elem, ind) => elem.addEventListener(
что такое ind?

2021-04-12 11:42 UTC, gavroman commented on src/boardPage/boardPageModel.js
> +    this.eventBus.subscribe(BoardPageEvent.openSettings, () => this.getBoardForSettings());
`this.eventBus.subscribe(BoardPageEvent.openSettings, this.getBoardForSettings);`

2021-04-12 11:47 UTC, gavroman commented on src/boardPage/boardPageView.js
> +    );
давай вызов нормально разобьем, по аргументу на строчку

2021-04-12 12:28 UTC, ZhukDima commented on src/utils/router.js
> +const standardizedPath = (path) => (typeof path === 'string' ? `/${(path.match(/[^/]{1,}/g) || []).join('/')}` : path);
если url выглядит как ////board//5 или board/5 или /board/5/ - он все их переводит в /board/5 и считает одинаковыми

2021-04-12 12:33 UTC, ZhukDima commented on src/utils/router.js
> +     * @type {[path, handler][]}
регулярки если они ключи - к строке приводятся 
![image](https://user-images.githubusercontent.com/55634168/114394855-5e104b00-9ba4-11eb-8e7b-3ec27cefdfa2.png)

2021-04-12 12:34 UTC, ZhukDima commented on src/index.js
> +router.addRoute(/^\/board\/(?<id>\d+)$/, ({ groups }) => boardPageController.start(+groups?.id));
Содержит все именнованные группы
![image](https://user-images.githubusercontent.com/55634168/114395009-8b5cf900-9ba4-11eb-8d3c-fbca30c0e7f8.png)

2021-04-12 12:39 UTC, ZhukDima commented on src/boardPage/boardPageView.js
> +    this.buttonsAddTask.forEach((elem, ind) => elem.addEventListener(
index

2021-04-12 12:48 UTC, ZhukDima commented on src/boardPage/boardPageModel.js
> +    this.eventBus.subscribe(BoardPageEvent.openSettings, () => this.getBoardForSettings());
если так сделать то потеряется `this` 
![image](https://user-images.githubusercontent.com/55634168/114396605-69647600-9ba6-11eb-9e29-51dac0c83fb7.png)
я поэтому и делал в какой-то момент `...all` потому что попробовал так прокидывать, но ничего не вышло

2021-04-12 13:32 UTC, gavroman commented on src/boardPage/boardPageModel.js
> +    this.eventBus.subscribe(BoardPageEvent.openSettings, () => this.getBoardForSettings());
правильно, чему должен быть равен this чтобы все работало и как это сделать?

2021-04-12 13:32 UTC, gavroman commented on src/boardPage/boardPageView.js
> +    this.buttonsAddTask.forEach((elem, ind) => elem.addEventListener(
тогда давай напишем index

2021-04-12 13:33 UTC, gavroman commented on src/utils/router.js
> +     * @type {[path, handler][]}
Правильно, ключами у объекта могут быть только строки, поэтому оно и приводится. Попробуй мапку

2021-04-12 13:35 UTC, gavroman commented on src/utils/router.js
> +const standardizedPath = (path) => (typeof path === 'string' ? `/${(path.match(/[^/]{1,}/g) || []).join('/')}` : path);
давай тогда без регулярки. url.split('/').filter((char) => char!=='/').join('/')

2021-04-12 15:12 UTC, ZhukDima commented on src/boardPage/boardPageModel.js
> +    this.eventBus.subscribe(BoardPageEvent.openSettings, () => this.getBoardForSettings());
Если обернуть в лямбда функцию - всё работает)

2021-04-12 15:20 UTC, gavroman commented on src/utils/router.js
> +  goWithoutHistory(path, ...data) {
для чего ...data?

2021-04-12 15:20 UTC, gavroman commented on src/utils/router.js
> +    const findElem = this.routes.find(({ path: key }) => (typeof key === 'string'
если все роуты регулярки, зачем проверка?

2021-04-12 15:21 UTC, gavroman commented on src/mainPage/mainPageModel.js
> +    this.eventBus.call(MainPageEvent.board, +boardNameId.slice(6));
договорились же убрать слайсы

2021-04-12 15:24 UTC, gavroman commented on src/boardPage/boardPageModel.js
> +    this.eventBus.subscribe(BoardPageEvent.openSettings, () => this.getBoardForSettings());
а почему с ней работает а без - нет и как сделать, чтоб работало?

2021-04-12 15:25 UTC, gavroman requested changes

2021-04-12 15:25 UTC, gavroman commented on src/boardPage/boardPageModel.js
> +    this.eventBus.subscribe(BoardPageEvent.addToFavorite, () => this.addToFavorite());
тут то же самое `this.eventBus.subscribe(BoardPageEvent.addToFavorite, this.addToFavorite);`

2021-04-12 15:31 UTC, ZhukDima commented on src/utils/router.js
> +  goWithoutHistory(path, ...data) {
ну вдруг кто-нибудь какие данные захочет пробросить))

2021-04-12 15:47 UTC, gavroman commented on src/utils/router.js
> +  goWithoutHistory(path, ...data) {
не должен захотеть. роутер принимает роут и идет по нему

2021-04-12 15:48 UTC, gavroman commented on src/utils/router.js
> +  goWithoutHistory(path, ...data) {
всю дату он должен достать из этого роута

2021-04-12 16:00 UTC, merged