Добавить навигацию на домашнюю страницу
frontend-park-mail-ru/2021_1_Execute pull request #50
Opened 2021-04-18 07:36 UTC by ZhukDima

2021-04-18 07:40 UTC, ZhukDima commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить навигацию на домашнюю страницу](https://trello.com/c/RFcnggZJ/74-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D1%8E-%D0%BD%D0%B0-%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D1%8E%D1%8E-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83)

2021-04-19 06:57 UTC, gavroman commented on src/profile/profile.handlebars
> +        <button id="change-data" class="menu-btn menu-btn-warning">Изменить
опять проблемки с переносом строк

2021-04-23 17:02 UTC, MKondakova requested changes
При нажатии на лого происходит обновление страницы

2021-04-25 20:24 UTC, MKondakova approved these changes

2021-05-01 08:15 UTC, merged